.\" Process this file with
.\" groff -man -Tascii gmbox.1
.\"
.TH simple 1 "Oct 2010" Linux "User Manuals"
.SH NAME
gmbox \- download music (mp3 format) from music.google.cn and play
.SH DESCRIPTION
.B There is no command option.

Note that you can only use it in Mainland China.
Or maybe considered not legal.
.SH AUTHOR
YunQiang Su <wzssyqa@gmail.com>
